apiVersion: batch/v1
kind: CronJob
metadata:
  name: shift-calendar-generator
  namespace: shift-calendar-generator
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: shift-calendar-generator
              image: dominik9917/shift-calendar-generator:v-3
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure # Usually better than 'Never' for transient errors
